### ISSUE TITLE
Develop a SEIR basic model in TerraML

### ISSUE THREAD

**Issue by tiagofml** [ufopleds/DengueMELib#24]
Develop a SEIR basic model in TerraML 2.0-RC-4

The model must contain three files:
- a XML file, used by DengueME to generate the graphical interface
- an input file, in TerraML, which will be automatically generated by DengueME, according to the XML file. Thereby, the same values of the XML for parameters for example, must be used in the input. This file will be used to test the source-code generation. 
- the model file

Restrictions:
- id of the model: ""tme_seir_basic_model"
- name of the main folder of the model: "tme_seir_basic_model"
- name of the folder of the model script: "tme_seir_basic_model_scripts"
- name of the XML: "tme_seir_basic_model.xml"
- name of the input file: "tme_seir_basic_model.lua"
- name of the model file: "tme_seir_basic_model.lua"

References:
- https://en.wikipedia.org/wiki/Compartmental_models_in_epidemiology#The_SEIR_model

**Comment by saraiva3** [comment]
I would also strongly advise to read the article that gave life to this concept: 
https://www.researchgate.net/publication/16673793_Seasonality_and_period-doubling_bifurcations_in_an_epidemic_model

**Comment by tiagofml** [comment]
@fellipedoprado in this version we can make the simplest possible model, without demography.
